export const display = [
  {
    name: "Formal Dress Shoes",
    type: "Shoes",
    price: 90,
    size: [8, 9, 10],
    otherImages: ["shoes4-front.jpg", "shoes4-side.jpg"],
    img: "./img/shoes4-main.jpg",
    id: "shoes109",
    description: "Elegant formal shoes crafted from premium leather.",
    rating: 4.9,
    comment: ["Look classy!", "Perfect for formal events", "Top quality."]
  },
  {
    name: "Cargo Shorts",
    type: "Short",
    price: 30,
    size: ["L", "XL"],
    otherImages: ["short3-front.jpg", "short3-back.jpg"],
    img: "./img/cargo-short].webp",
    id: "short209",
    description: "Utility cargo shorts with plenty of pockets.",
    rating: 4.6,
    comment: ["Love the pockets!", "Great for casual wear", "Nice fit."]
  },
  {
    name: "Leather Backpack",
    type: "Bag",
    price: 65,
    size: ["Medium"],
    otherImages: ["bag1-front.jpg", "bag1-back.jpg"],
    img: "./img/bag1-main.jpg",
    id: "bag104",
    description: "A stylish leather backpack with multiple compartments.",
    rating: 4.8,
    comment: ["Spacious and durable!", "Looks great", "Perfect for work."]
  },
  {
    name: "Chino Pants",
    type: "Trouser",
    price: 35,
    size: ["M", "L", "XL"],
    otherImages: ["trouser1-front.jpg", "trouser1-back.jpg"],
    img: "./img/trouser1-main.jpg",
    id: "trouser202",
    description: "Slim-fit chinos available in various colors.",
    rating: 4.5,
    comment: ["Great fit!", "Very comfortable", "Love the colors!"]
  },
  {
    name: "Classic White Shirt",
    type: "Shirt",
    price: 25,
    size: ["S", "M", "L"],
    otherImages: ["shirt1-front.jpg", "shirt1-back.jpg"],
    img: "./img/shirt1-main.webp",
    id: "shirt301",
    description: "A classic white shirt made from 100% cotton. Perfect for any occasion.",
    rating: 4.5,
    comment: ["Great quality!", "Fits well", "Love the fabric!"]
  },
  {
    name: "Athletic Shorts",
    type: "Short",
    price: 20,
    size: ["M", "L", "XL"],
    otherImages: ["short2-front.jpg", "short2-back.jpg"],
    img: "./img/short2-main.jpeg",
    id: "short208",
    description: "Breathable athletic shorts ideal for sports and workouts.",
    rating: 4.7,
    comment: ["Very lightweight!", "Good for running", "Breathable fabric."]
  },
  {
    name: "Running Sneakers",
    type: "Shoes",
    price: 50,
    size: [7, 8, 9, 10],
    otherImages: ["shoes1-front.jpg", "shoes1-side.jpg"],
    img: "./img/shoes1-main.webp",
    id: "shoes101",
    description: "Lightweight running sneakers with excellent grip and comfort.",
    rating: 4.6,
    comment: ["Very comfortable!", "Perfect for jogging!", "Great shoes."]
  },
  {
    name: "Sports Duffel Bag",
    type: "Bag",
    price: 55,
    size: ["Large"],
    otherImages: ["bag3-front.jpg", "bag3-side.jpg"],
    img: "./img/bag3-main.jpeg",
    id: "bag107",
    description: "Spacious duffel bag ideal for gym and sports activities.",
    rating: 4.7,
    comment: ["Great for the gym!", "Fits everything I need", "Good quality."]
  },
  {
    name: "Floral Printed Shirt",
    type: "Shirt",
    price: 35,
    size: ["S", "M"],
    otherImages: ["shirt3-front.jpg", "shirt3-back.jpg"],
    img: "./img/shirt3-main.jpg",
    id: "shirt303",
    description: "Bright and colorful floral printed shirt perfect for summer.",
    rating: 4.8,
    comment: ["Perfect for vacation!", "Nice material", "Great for summer."]
  },
  {
    name: "Leather Boots",
    type: "Shoes",
    price: 80,
    size: [9, 10, 11],
    otherImages: ["shoes2-front.jpg", "shoes2-side.jpg"],
    img: "./img/shoes2-main.webp",
    id: "shoes102",
    description: "Stylish leather boots for a rugged look.",
    rating: 4.8,
    comment: ["Look fantastic!", "Very durable", "Great for winter."]
  },
  {
    name: "Denim Shorts",
    type: "Short",
    price: 25,
    size: ["S", "M", "L"],
    otherImages: ["short1-front.jpg", "short1-back.jpg"],
    img: "./img/short1-main.jpg",
    id: "short206",
    description: "Classic denim shorts perfect for a casual look.",
    rating: 4.5,
    comment: ["Great for summer!", "Comfortable fit", "Nice style."]
  },
  {
    name: "Blue Striped Shirt",
    type: "Shirt",
    price: 30,
    size: ["M", "L", "XL"],
    otherImages: ["shirt2-front.jpg", "shirt2-back.jpg"],
    img: "./img/shirt2-main.jpg",
    id: "shirt302",
    description: "A stylish blue striped shirt with a modern fit.",
    rating: 4.7,
    comment: ["Very stylish!", "Looks amazing!", "Great for casual wear."]
  }
];
